[build]
  command = "yarn build:ci"
  publish = "out"

[build.environment]
  NODE_VERSION = "16.19.0"
  NETLIFY_NEXT_PLUGIN_SKIP = true

[context.production.environment]
  SENTRY_ENVIRONMENT = "production"
  NEXT_PUBLIC_SENTRY_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  SENTRY_ENVIRONMENT = "deploy-preview"
  NEXT_PUBLIC_SENTRY_ENVIRONMENT = "deploy-preview"

[[plugins]]
  package = "@netlify/plugin-nextjs"
