[build]
command = "pnpm build:ci"
publish = "out"

[build.environment]
NODE_VERSION = "18.17.1"
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[context.production.environment]
SENTRY_ENVIRONMENT = "production"
ANALYZE = "true"

[context.deploy-preview.environment]
SENTRY_ENVIRONMENT = "deploy-preview"
ANALYZE = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = "404.html"

  [[plugins.inputs.audits]]
    path = "contribua.html"

  [[plugins.inputs.audits]]
    path = "sobre.html"
  
  [[plugins.inputs.audits]]
    path = "busca.html"
